language: bash
sudo: required

os:
    - linux
    - osx

script:
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then sudo PREFIX=/usr/local make install; else sudo make install; fi
    - neofetch --test --ascii --color_blocks off
