language: bash
sudo: required

os:
    - linux
    - osx

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install screenresolution; fi

script:
    - time ./neofetch --travis -v
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then shellcheck neofetch; fi
    # Check for lines longer than 100 chars.
    - if grep '.\{101\}' neofetch; then (exit 1); else (exit 0); fi
